### ISSUE TITLE
Can't see tasks I've added

### ISSUE THREAD

**Issue by chammaaomar** [shivamanipatil/GoTodo#1]
Hi!
## Listing tasks
When I use `./main help` I see that I can add a task, but there is no way to actually list all the tasks I've added, or inspect the task I've just added, as far as I can tell. A `./main list` usage would be helpful, and then maybe a filter like `./main list -p` would show only the pending ones.

## Task ID
We can access tasks by ID, but when I add a task, like `./main add "buy a gopher plush"` I don't even know its ID. It would be useful to somehow print the id to the terminal when a task is added.

Thank you!

**Comment by shivamanipatil** [comment]
Hey, Sorry for that I forgot to update the help menu. Actually ./main list does list the tasks and there are ids to tasks on the leftmost column for tasks. And currently, the pending number of tasks is shown I will also add an option to show the pending tasks.

**Comment by chammaaomar** [comment]
That's great! I noticed in the source code there was fatih/color, but I couldn't see any colours 😝. Alright thanks!

**Comment by shivamanipatil** [comment]
Hey, I have updated the help menu and also added listPending tasks functionality. You can check it out.
